name: Practica workshop

on:
  push:
    branches:
      - main
      - fin

  pull_request:
    branches:
      - main

jobs:
  Test:
    name: Jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci
